### ISSUE TITLE
problem with saveDatasheet - append=F

### ISSUE THREAD

**Issue by josie-hughes** [syncrosim/rsyncrosim#12] opened 2020-07-28 19:54 UTC
I can no longer overwrite project scope datasheets by setting append=F.
It looks like the append=F argument is being ignored.
Please let me know when you address this - my workflow depends on being able to overwrite project datasheets.

**Comment by VLucet** [comment] 2020-07-28 20:19
Hi @josie-hughes, are you using the CRAN version? I have never used this feature before so it's possible that because I am not familiar with it, I have introduced a bug in the code during the submission process to CRAN. Maybe @alexembrey could be of better help on this. I have looked at the git history of `saveDatasheet` and I cannot pinpoint where a breaking change would have happened. A reproducible example would help me.

**Comment by alexembrey** [comment] 2020-07-28 20:43
You can't overwrite project scoped data using append=F.  (There's a small note in the help for saveDatasheet() about how it can have different behavior depending on the scope, but it's not made very clear what the differences are...)  

The way to do this is by using the "delete()" function.  For example:  
**delete(proj, datasheet = "stsim_Stratum")**

**Comment by josie-hughes** [comment] 2020-07-28 20:58
Thanks @VLucet and @alexembrey . 
I tried deleting - it fails when datasheet="Stratum", and succeeds when datasheet="stsim_Stratum". Not consistent with other functions that no longer require stsim prefix.
Here is a reproducible example. 
For others  it would be helpful to include a warning that append argument is ignored for project scope datasheets, along with suggestion to use delete.
############
library(rsyncrosim)

cSession = session(printCmd=F)
testLib = ssimLibrary("test",session=cSession)
testProj = project(testLib,"testProj")

cSheet ="Stratum"
saveDatasheet(testProj,data.frame(Name="LS",ID=1),name=cSheet)
delete(ssimLibrary(testProj),project=1,datasheet=cSheet,force=T) #This fails.

delete(ssimLibrary(testProj),project=1,datasheet="stsim_Stratum",force=T) #This works

**Comment by alexembrey** [comment] 2020-07-28 21:25
You are right - an explicit namespace should not be required.  I've created a JIRA bug about this.  Hopefully it will get fixed for the next release of RSyncroSim.

**Comment by josie-hughes** [comment] 2020-07-28 21:27
In the meantime I will go ahead and use my new namespace knowledge. Thx.

**Comment by katieb1** [comment] 2024-03-06 19:23
Closing as this has since been fixed.

**Closed as completed** 2024-03-06 19:22 UTC
Labels: bug
